"""empty message

Revision ID: d0d31f7dfd8c
Revises: 3c8307334f5e
Create Date: 2021-02-04 13:07:22.556717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0d31f7dfd8c'
down_revision = '3c8307334f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.add_column('users', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('name', sa.String(length=24), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=24), nullable=True))
    op.add_column('users', sa.Column('user_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_column('users', 'name')
    op.drop_column('users', 'id')
    op.create_table('tasks',
    sa.Column('task_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='tasks_ibfk_1'),
    sa.PrimaryKeyConstraint('task_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
